version: '3.8'

services:
  hamclock-backend:
    build:
      context: .
      dockerfile: Containerfile
    container_name: hamclock-backend
    command: python3 -u server.py
    ports:
      - "9086:9086"
    volumes:
      - ./processed_data:/app/processed_data
    environment:
      - PORT=9086

  hamclock-proxy:
    build:
      context: .
      dockerfile: Containerfile
    container_name: hamclock-proxy
    command: python3 -u shadow_proxy/proxy.py
    ports:
      - "9085:9085"
    volumes:
      - ./captured_data:/app/captured_data
    environment:
      - PORT=9085
    depends_on:
      - hamclock-backend

# Note: The HamClock client (binary) is typically run on the host 
# due to its GUI requirements, but it could be containerized if 
# using a VNC/X11 bridge.
